version: "3.8"

services:

  maildev:
    image: maildev/maildev
    container_name: maildev_covid19_twitter
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      - dev
  www:
    build: ./
    container_name: www_covid19_twitter
    ports:
      - "9000:80"
    volumes:
      - ./vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev
networks:
  dev:

volumes:
  db-data: